// The bootstrap sign-in seed: an owner row and one hashed magic-link token, written straight
// into the deployed AUTH_DB with `wrangler d1 execute`, so the admin's first sign-in needs no
// email loop. This rides the engine's own tables and hashing with no engine change: the token is
// generated the same way `src/lib/auth/crypto.ts` generates one, hashed the same way, and given
// the same ten-minute TTL, so the confirm page's own lookup (`src/lib/auth/store.ts`) finds
// exactly what this seed wrote. The `session` table is never touched; the confirm click mints the
// session through the engine's own code path.
import { randomBytes, createHash } from 'node:crypto';
import { runWrangler } from './exec.mjs';
import { cloudflareError } from './catalogue.mjs';

/** The engine's own magic-token lifetime (`TOKEN_TTL_MS` in `src/lib/auth/crypto.ts`). */
const TOKEN_TTL_MS = 10 * 60 * 1000;

/**
 * Reduce a child's stderr to its last few non-empty lines, for the catalogue's `detail` param.
 * @param {string} stderr the child's captured stderr
 * @param {number} [maxLines] how many trailing lines to keep
 * @returns {string} the trailing lines, joined back with newlines; '' when stderr was empty
 */
function trailingStderr(stderr, maxLines = 8) {
  const lines = stderr
    .split('\n')
    .map((line) => line.trimEnd())
    .filter((line) => line.length > 0);
  return lines.slice(-maxLines).join('\n');
}

/**
 * Escape a value for embedding in a single-quoted SQL string literal, by doubling any single
 * quote it contains. The email is the only user-supplied value in this seed's SQL; the hash and
 * the numbers are generated by this function and never need escaping.
 * @param {string} value the raw value to embed
 * @returns {string} the value with every `'` doubled
 */
function escapeSqlString(value) {
  return value.replace(/'/g, "''");
}

/**
 * Normalize an email the way the engine's own store does on every path
 * (`normalizeEmail` in `src/lib/auth/store.ts`), so this seed writes exactly what a later lookup
 * finds.
 * @param {string} email the raw address, as the admin typed it
 * @returns {string} the trimmed, lowercased address
 */
function normalizeEmail(email) {
  return email.trim().toLowerCase();
}

/**
 * Seed the owner's `editor` row and one bootstrap magic-link token directly into the deployed
 * AUTH_DB, so opening the returned confirm path signs the admin in with no email round trip.
 * @param {object} args
 * @param {string} args.dir the scaffold root, used as the wrangler invocation's cwd
 * @param {string} args.email the admin's sign-in address, normalized before it is written
 * @param {(line: string) => void} args.log receives progress lines
 * @param {number} [args.now] the current time in epoch milliseconds, injectable for tests;
 *  defaults to `Date.now()`
 * @returns {Promise<{ confirmPath: string }>} the site-relative confirm URL carrying the raw
 *  token; the token exists only in this returned string and is never written to disk or state
 */
export async function seedOwnerAndToken({ dir, email, log, now = Date.now() }) {
  const normalizedEmail = normalizeEmail(email);
  const displayName = normalizedEmail.slice(0, normalizedEmail.indexOf('@'));
  const escapedEmail = escapeSqlString(normalizedEmail);
  const escapedDisplayName = escapeSqlString(displayName);

  const token = randomBytes(32).toString('base64url');
  const tokenHash = createHash('sha256').update(token).digest('hex');
  const expiresAt = now + TOKEN_TTL_MS;

  const sql =
    `INSERT INTO editor (email, display_name, role, created_at)\n` +
    `  VALUES ('${escapedEmail}', '${escapedDisplayName}', 'owner', ${now})\n` +
    `  ON CONFLICT(email) DO NOTHING;\n` +
    `DELETE FROM magic_token WHERE email = '${escapedEmail}';\n` +
    `INSERT INTO magic_token (token_hash, email, expires_at, created_at)\n` +
    `  VALUES ('${tokenHash}', '${escapedEmail}', ${expiresAt}, ${now});`;

  log("Writing your sign-in row to the site's database.");
  const result = await runWrangler(['d1', 'execute', 'AUTH_DB', '--remote', '--command', sql], {
    cwd: dir,
    log
  });
  if (result.code !== 0) {
    throw cloudflareError('seed-failed', { dir, detail: trailingStderr(result.stderr) });
  }

  return { confirmPath: '/admin/auth/confirm?token=' + encodeURIComponent(token) };
}
