// The bootstrap sign-in seed: an owner row and one hashed magic-link token, written straight
// into the deployed AUTH_DB with `wrangler d1 execute`, so the admin's first sign-in needs no
// email loop. This rides the engine's own tables and hashing with no engine change: the token is
// generated the same way `src/lib/auth/crypto.ts` generates one, hashed the same way, and given
// the same ten-minute TTL, so the confirm page's own lookup (`src/lib/auth/store.ts`) finds
// exactly what this seed wrote. The `session` table is never touched; the confirm click mints the
// session through the engine's own code path.
//
// The seed's SQL encodes the same trust the engine does: the owner insert only ever fires on a
// genuinely empty allowlist (`insertOwnerIfEmpty` in `src/lib/auth/store.ts`), and the token
// insert only ever fires for an address the editor table already carries, whether it was already
// there or the owner insert just added it. A non-matching email against an already-populated
// allowlist grants nothing, the same trust `src/lib/sveltekit/auth-routes.ts` describes for the
// engine's own bootstrap path.
import { randomBytes, createHash } from 'node:crypto';
import { runWrangler, accountEnv } from './exec.mjs';
import { cloudflareError, trailingStderr } from './catalogue.mjs';

/** The engine's own magic-token lifetime (`TOKEN_TTL_MS` in `src/lib/auth/crypto.ts`). */
const TOKEN_TTL_MS = 10 * 60 * 1000;

/**
 * What to print once a seeded sign-in link has been opened. Both callers that open one (the
 * chapter's own sign-in action and bin.mjs's `--sign-in` recovery) print this, and it lives
 * beside the lifetime it quotes so a change to `TOKEN_TTL_MS` cannot leave one of them promising
 * the old number.
 */
export const SIGN_IN_OPENED_NOTICE =
  'A sign-in page just opened; click Sign in there. The link works for ten minutes; if it ' +
  'expires, re-run with --sign-in for a fresh one.';

/**
 * Escape a value for embedding in a single-quoted SQL string literal, by doubling any single
 * quote it contains. The email is the only user-supplied value in this seed's SQL; the hash and
 * the numbers are generated by this function and never need escaping.
 * @param {string} value the raw value to embed
 * @returns {string} the value with every `'` doubled
 */
function escapeSqlString(value) {
  return value.replace(/'/g, "''");
}

/**
 * Normalize an email the way the engine's own store does on every path
 * (`normalizeEmail` in `src/lib/auth/store.ts`), so this seed writes exactly what a later lookup
 * finds.
 * @param {string} email the raw address, as the admin typed it
 * @returns {string} the trimmed, lowercased address
 */
function normalizeEmail(email) {
  return email.trim().toLowerCase();
}

/**
 * Parse a `wrangler d1 execute --json` stdout into its array of per-statement results. Some
 * wrangler versions print a notice line ahead of the JSON (an agent-skills banner, observed on
 * this machine's toolchain for other `--json` subcommands), so this slices from the first `[`
 * rather than trusting the whole stdout to already be JSON.
 * @param {string} stdout the child's captured stdout
 * @returns {Array<{ meta?: { changes?: number } }> | null} the parsed array, or null when the
 *  output carried nothing that parses as one
 */
function parseD1JsonResults(stdout) {
  const start = stdout.indexOf('[');
  if (start === -1) return null;
  try {
    const parsed = JSON.parse(stdout.slice(start));
    return Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

/**
 * Seed the owner's `editor` row and one bootstrap magic-link token directly into the deployed
 * AUTH_DB, so opening the returned confirm path signs the admin in with no email round trip.
 * @param {object} args
 * @param {string} args.dir the scaffold root, used as the wrangler invocation's cwd
 * @param {string} args.email the admin's sign-in address, normalized before it is written
 * @param {(line: string) => void} args.log receives progress lines
 * @param {number} [args.now] the current time in epoch milliseconds, injectable for tests;
 *  defaults to `Date.now()`
 * @param {string} [args.accountId] the Cloudflare account the deployed database lives in, from
 *  `ensureAccountId`; when given, it is passed to wrangler as `CLOUDFLARE_ACCOUNT_ID`
 * @returns {Promise<{ confirmPath: string }>} the site-relative confirm URL carrying the raw
 *  token; the token exists only in this returned string and is never written to disk or state
 */
export async function seedOwnerAndToken({ dir, email, log, now = Date.now(), accountId }) {
  const normalizedEmail = normalizeEmail(email);
  const displayName = normalizedEmail.slice(0, normalizedEmail.indexOf('@'));
  const escapedEmail = escapeSqlString(normalizedEmail);
  const escapedDisplayName = escapeSqlString(displayName);

  const token = randomBytes(32).toString('base64url');
  const tokenHash = createHash('sha256').update(token).digest('hex');
  const expiresAt = now + TOKEN_TTL_MS;

  // The owner insert fires only when the allowlist is empty (WHERE NOT EXISTS), mirroring
  // insertOwnerIfEmpty exactly, and the token insert fires only for an address the editor table
  // already carries (WHERE EXISTS), whether it was already there or the insert above just added
  // it. An address that is neither the sole owner-to-be nor an existing editor gets nothing.
  const sql =
    `INSERT INTO editor (email, display_name, role, created_at)\n` +
    `  SELECT '${escapedEmail}', '${escapedDisplayName}', 'owner', ${now}\n` +
    `  WHERE NOT EXISTS (SELECT 1 FROM editor);\n` +
    `DELETE FROM magic_token WHERE email = '${escapedEmail}';\n` +
    `INSERT INTO magic_token (token_hash, email, expires_at, created_at)\n` +
    `  SELECT '${tokenHash}', '${escapedEmail}', ${expiresAt}, ${now}\n` +
    `  WHERE EXISTS (SELECT 1 FROM editor WHERE email = '${escapedEmail}');`;

  log("Writing your sign-in row to the site's database.");
  // The `--json` payload on this command's stdout belongs to the row-count check below, not to
  // the admin. A no-op log keeps all three raw result objects out of the terminal.
  const result = await runWrangler(
    ['d1', 'execute', 'AUTH_DB', '--remote', '--command', sql, '--json'],
    { cwd: dir, log: () => {}, ...accountEnv(accountId) },
  );
  if (result.code !== 0) {
    throw cloudflareError('seed-failed', { dir, detail: trailingStderr(result.stderr) });
  }

  // A zero exit can still have granted nothing: the WHERE EXISTS guard above makes the token
  // insert itself conditional, so a seed against an already-populated allowlist that does not
  // carry this address writes no row at all. Handing back a confirm link in that case would be a
  // dead link the admin has no way to diagnose, so this checks the token insert's own row count
  // (the last of the three statements) rather than trusting the exit code alone.
  const results = parseD1JsonResults(result.stdout);
  const tokenInsertResult = results?.[results.length - 1];
  const tokenWasWritten = (tokenInsertResult?.meta?.changes ?? 0) > 0;
  if (!tokenWasWritten) {
    throw cloudflareError('seed-failed', { dir, reason: 'not-allowlisted', email: normalizedEmail });
  }

  return { confirmPath: '/admin/auth/confirm?token=' + encodeURIComponent(token) };
}
