/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: b4be780c75bf09e0effe15fc18d98e43)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	AUTH_DB: D1Database;
	APP_DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	PUBLIC_ORIGIN: "http://localhost:4173";
	GITHUB_APP_ID: string;
	GITHUB_APP_INSTALLATION_ID: string;
	GITHUB_APP_PRIVATE_KEY_B64: string;
	ANTHROPIC_API_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "GITHUB_APP_ID" | "GITHUB_APP_INSTALLATION_ID" | "GITHUB_APP_PRIVATE_KEY_B64" | "ANTHROPIC_API_KEY">> {}
}
