// Command copylist prints every operator-facing string this module's messages and fix tables
// carry, grouped by package and sorted, with no run required: tool/docs/design/copy-standard.md
// section 4.3's own golden generator. `make copy-list` writes its output to
// tool/testdata/copy.golden.md, and `make check-copy` asserts a fresh run matches the committed
// file, so a new string cannot land invisibly.
//
// copylist reads the tables as Go values rather than grepping source, which is why it is a
// second binary in this module rather than a shell script: tool/docs/design/copy-standard.md
// section 4.3 calls it "the --list flag ... ported", and a Go value is what a shell script
// cannot read. The release still builds only ./cmd/cairn; this binary exists for the golden and
// for `make copy-list`, never for an operator to install.
package main

import (
	"fmt"
	"slices"
	"strings"

	"github.com/glw907/cairn-cms/tool/internal/health"
)

// packageCatalogue is one package's own sorted, deduplicated set of operator-facing strings.
type packageCatalogue struct {
	name    string
	entries []string
}

// catalogues returns every package's own catalogue, in a fixed package order: today only
// health carries operator-facing strings, and a later task's cmd/cairn table adds a second
// entry here rather than a second binary.
func catalogues() []packageCatalogue {
	return []packageCatalogue{
		{name: "health", entries: sortedUnique(append(health.Catalogue(), health.FixLines()...))},
	}
}

// sortedUnique returns entries sorted and de-duplicated, so a string two tables happen to share
// (a fix line reused verbatim as a detail, for instance) prints once.
func sortedUnique(entries []string) []string {
	sorted := slices.Clone(entries)
	slices.Sort(sorted)
	return slices.Compact(sorted)
}

// render builds the golden's own Markdown text from every package's catalogue, the single
// function main and this file's own test both call, so the committed file and a fresh run are
// compared against the same rendering rather than two copies of it.
func render() string {
	var b strings.Builder
	b.WriteString("# cairn CLI operator-facing copy catalogue\n\n")
	b.WriteString("Generated by `make copy-list`. Do not edit by hand; run `make copy-list` again\n")
	b.WriteString("and commit the diff.\n")

	for _, pkg := range catalogues() {
		b.WriteString("\n## " + pkg.name + "\n\n")
		for _, entry := range pkg.entries {
			b.WriteString("- " + entry + "\n")
		}
	}
	return b.String()
}

func main() {
	fmt.Print(render())
}
