package doctor

import (
	"strings"
	"testing"

	"github.com/glw907/cairn-cms/tool/internal/spine"
)

// The fixtures below are the config.no-referrer-blanket corpus.
const (
	// hooksBlanket is a site-wide, unconditional write: no pathname guard anywhere near the header
	// set, so the heuristic reads it as blanket.
	hooksBlanket = `import type { Handle } from '@sveltejs/kit';
export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  response.headers.set('Referrer-Policy', 'no-referrer');
  return response;
};
`
	// hooksScoped is the same header, scoped to a token-bearing route the site itself checks.
	hooksScoped = `import type { Handle } from '@sveltejs/kit';
export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  if (event.url.pathname.startsWith('/admin')) {
    response.headers.set('Referrer-Policy', 'no-referrer');
  }
  return response;
};
`
	// headersBlanket is a catch-all _headers block carrying no-referrer.
	headersBlanket = "/*\n  Referrer-Policy: no-referrer\n  X-Frame-Options: DENY\n"
	// headersScoped scopes no-referrer to /admin/* only.
	headersScoped = "/admin/*\n  Referrer-Policy: no-referrer\n\n/*\n  X-Frame-Options: DENY\n"
	// headersBlanketWithComment is the named gap case: a # comment interleaved INSIDE a block,
	// between the path line and its header line. Without the comment-skip, this line reads as an
	// un-indented path line and splits the real /* block in two.
	headersBlanketWithComment = "/*\n# generated by @sveltejs/adapter-cloudflare\n  Referrer-Policy: no-referrer\n"
	// headersBlanketAbsoluteURL writes the catch-all glob as the pathname of an absolute URL, which
	// Cloudflare also accepts.
	headersBlanketAbsoluteURL = "https://example.com/*\n  Referrer-Policy: no-referrer\n"
	// headersBlanketList is the named gap case: no-referrer is the last (effective) token of a
	// comma-separated fallback list.
	headersBlanketList = "/*\n  Referrer-Policy: strict-origin, no-referrer\n"
	// headersListNotLast is the mirror case: no-referrer appears but is not the last token, so a
	// compliant browser never resolves to it.
	headersListNotLast = "/*\n  Referrer-Policy: no-referrer, strict-origin-when-cross-origin\n"
	// hooksBlockComment merely shows the header in a code sample inside a block comment.
	hooksBlockComment = `import type { Handle } from '@sveltejs/kit';
export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  /* response.headers.set('Referrer-Policy', 'no-referrer'); */
  return response;
};
`
	// hooksLineComment warns about the policy in a line comment, not setting it.
	hooksLineComment = `import type { Handle } from '@sveltejs/kit';
export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  // response.headers.set('Referrer-Policy', 'no-referrer'); // do not do this site-wide
  return response;
};
`
	// hooksScopedRouteID is the named gap case: scoped with route.id rather than pathname.
	hooksScopedRouteID = `import type { Handle } from '@sveltejs/kit';
export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  if (event.route.id?.startsWith('/(admin)')) {
    response.headers.set('Referrer-Policy', 'no-referrer');
  }
  return response;
};
`
	// hooksScopedURLHref is the named gap case: scoped with url.href rather than pathname.
	hooksScopedURLHref = `import type { Handle } from '@sveltejs/kit';
export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  if (event.url.href.includes('/admin')) {
    response.headers.set('Referrer-Policy', 'no-referrer');
  }
  return response;
};
`
)

// TestConfigNoReferrerBlanket proves config.no-referrer-blanket's three reachable statuses (pass,
// fail, skip) over the corpus above.
func TestConfigNoReferrerBlanket(t *testing.T) {
	tests := []struct {
		name          string
		files         map[string]string
		wantStatus    Status
		wantDetailHas []string
	}{
		{
			name:          "fail: site-wide policy in src/hooks.server.ts",
			files:         map[string]string{"src/hooks.server.ts": hooksBlanket},
			wantStatus:    StatusFail,
			wantDetailHas: []string{"src/hooks.server.ts", "Origin: null", "strict-origin-when-cross-origin", "heuristic"},
		},
		{
			name:          "fail: site-wide policy in static/_headers",
			files:         map[string]string{"static/_headers": headersBlanket},
			wantStatus:    StatusFail,
			wantDetailHas: []string{"static/_headers", "Origin: null", "strict-origin-when-cross-origin"},
		},
		{
			name:       "pass: scoped to a token-bearing route in static/_headers",
			files:      map[string]string{"static/_headers": headersScoped},
			wantStatus: StatusPass,
		},
		{
			name:       "pass: scoped to a token-bearing route in src/hooks.server.ts",
			files:      map[string]string{"src/hooks.server.ts": hooksScoped},
			wantStatus: StatusPass,
		},
		{
			name: "pass: neither source mentions no-referrer at all",
			files: map[string]string{
				"src/hooks.server.ts": "export const handle = ({ event, resolve }) => resolve(event);\n",
				"static/_headers":     "/*\n  X-Frame-Options: DENY\n",
			},
			wantStatus: StatusPass,
		},
		{
			name:          "skip: neither source is readable",
			files:         map[string]string{},
			wantStatus:    StatusSkip,
			wantDetailHas: []string{"src/hooks.server.ts", "static/_headers", "strict-origin-when-cross-origin", "is-it-working.md#scope-a-site-wide-no-referrer-policy"},
		},
		{
			name:       "fail: reads src/hooks.server.js when the .ts spelling is absent",
			files:      map[string]string{"src/hooks.server.js": hooksBlanket},
			wantStatus: StatusFail,
		},
		{
			name:       "gap case: fails on a blanket _headers block with a # comment interleaved inside it",
			files:      map[string]string{"static/_headers": headersBlanketWithComment},
			wantStatus: StatusFail,
		},
		{
			name:       "fails on a catch-all path written as the pathname of an absolute URL",
			files:      map[string]string{"static/_headers": headersBlanketAbsoluteURL},
			wantStatus: StatusFail,
		},
		{
			name:       "gap case: fails when no-referrer is the last token of a comma-separated policy list",
			files:      map[string]string{"static/_headers": headersBlanketList},
			wantStatus: StatusFail,
		},
		{
			name:       "passes when no-referrer appears in a list but is not the last token",
			files:      map[string]string{"static/_headers": headersListNotLast},
			wantStatus: StatusPass,
		},
		{
			name:       "passes when the only mention is inside a block comment",
			files:      map[string]string{"src/hooks.server.ts": hooksBlockComment},
			wantStatus: StatusPass,
		},
		{
			name:       "passes when the only mention is inside a line comment",
			files:      map[string]string{"src/hooks.server.ts": hooksLineComment},
			wantStatus: StatusPass,
		},
		{
			name:       "gap case: passes when scoped with route.id rather than pathname",
			files:      map[string]string{"src/hooks.server.ts": hooksScopedRouteID},
			wantStatus: StatusPass,
		},
		{
			name:       "gap case: passes when scoped with url.href rather than pathname",
			files:      map[string]string{"src/hooks.server.ts": hooksScopedURLHref},
			wantStatus: StatusPass,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := snapshotWithFiles(t, tt.files)
			result := runCheck(configNoReferrerBlanket, s).Result
			if result.Status != tt.wantStatus {
				t.Fatalf("Status = %v, want %v (detail %q)", result.Status, tt.wantStatus, result.Detail)
			}
			for _, want := range tt.wantDetailHas {
				if !strings.Contains(result.Detail, want) {
					t.Errorf("Detail = %q, want it to contain %q", result.Detail, want)
				}
			}
			if tt.wantStatus == StatusFail && result.Severity != spine.WarningFailure {
				t.Errorf("Severity = %v, want spine.WarningFailure", result.Severity)
			}
		})
	}
}

// TestConfigNoReferrerBlanketNamesSourcesOnPass proves that a pass names which of the two header
// sources it actually read.
func TestConfigNoReferrerBlanketNamesSourcesOnPass(t *testing.T) {
	s := snapshotWithFiles(t, map[string]string{"static/_headers": headersScoped})
	result := configNoReferrerBlanket.Run(s)
	if result.Status != StatusPass {
		t.Fatalf("Status = %v, want StatusPass", result.Status)
	}
	if !strings.Contains(result.Detail, "read static/_headers") {
		t.Errorf("Detail = %q, want it to contain %q", result.Detail, "read static/_headers")
	}
	if !strings.Contains(result.Detail, "src/hooks.server.ts (or .js) not found") {
		t.Errorf("Detail = %q, want it to contain %q", result.Detail, "src/hooks.server.ts (or .js) not found")
	}
}

func TestConfigNoReferrerBlanketConditionID(t *testing.T) {
	if string(configNoReferrerBlanket.Condition) != "config.no-referrer-blanket" {
		t.Errorf("Condition = %q, want config.no-referrer-blanket", configNoReferrerBlanket.Condition)
	}
}

// TestIsCatchAllHeadersPathGapCase proves the net/url port still recognizes the absolute-URL
// spelling of the catch-all glob.
func TestIsCatchAllHeadersPathGapCase(t *testing.T) {
	if !isCatchAllHeadersPath("https://example.com/*") {
		t.Fatal("isCatchAllHeadersPath(https://example.com/*) = false, want true")
	}
	if isCatchAllHeadersPath("/admin/*") {
		t.Fatal("isCatchAllHeadersPath(/admin/*) = true, want false")
	}
}

// TestHooksSetsBlanketNoReferrerGapCase is the named gap case: a route-scoped no-referrer write
// within the six-line window above must not read as blanket. Proven directly against the helper,
// which fails without the window scan: a bare mention-of-both-tokens match finds the write and
// returns true regardless of the nearby pathname guard.
func TestHooksSetsBlanketNoReferrerGapCase(t *testing.T) {
	if hooksSetsBlanketNoReferrer(hooksScoped) {
		t.Fatal("hooksSetsBlanketNoReferrer(hooksScoped) = true, want false: the write is scoped by pathname within the six-line window")
	}
	if !hooksSetsBlanketNoReferrer(hooksBlanket) {
		t.Fatal("hooksSetsBlanketNoReferrer(hooksBlanket) = false, want true: no scoping guard is present")
	}
}

// TestHooksSetsBlanketNoReferrerKeepsQuotedURLs proves a quoted URL holding two slashes is not
// read as a line comment: the setting that follows the URL on the same line, and the setting on
// the next line, are both still seen, while a real comment naming the policy stays ignored.
func TestHooksSetsBlanketNoReferrerKeepsQuotedURLs(t *testing.T) {
	tests := []struct {
		name string
		hook string
		want bool
	}{
		{
			name: "setting follows a quoted URL on the same line",
			hook: "const home = 'https://example.com'; event.setHeaders({ 'Referrer-Policy': 'no-referrer' });\n",
			want: true,
		},
		{
			name: "setting on the line after a quoted URL",
			hook: "const home = 'https://example.com';\nevent.setHeaders({ 'Referrer-Policy': 'no-referrer' });\n",
			want: true,
		},
		{
			name: "setting named only in a line comment",
			hook: "const home = 'https://example.com'; // 'Referrer-Policy': 'no-referrer'\n",
			want: false,
		},
		{
			name: "setting named only in a block comment spanning lines",
			hook: "/* the 'Referrer-Policy'\n  is 'no-referrer' */\nconst home = 'https://example.com';\n",
			want: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := hooksSetsBlanketNoReferrer(tt.hook); got != tt.want {
				t.Errorf("hooksSetsBlanketNoReferrer(%q) = %v, want %v", tt.hook, got, tt.want)
			}
		})
	}
}

// TestParseHeadersFileGapCase is the named gap case: a comment line interleaved inside a
// _headers block must not split it. Proven directly against the parser, which fails without the
// comment-skip: a naive line scan reads the # line as a new path line and starts a second,
// header-less block, losing the real block's headers.
func TestParseHeadersFileGapCase(t *testing.T) {
	blocks := parseHeadersFile(headersBlanketWithComment)
	if len(blocks) != 1 {
		t.Fatalf("parseHeadersFile returned %d blocks, want 1 (the comment must not split the block): %+v", len(blocks), blocks)
	}
	if blocks[0].path != "/*" {
		t.Errorf("blocks[0].path = %q, want /*", blocks[0].path)
	}
	if len(blocks[0].headers) != 1 || blocks[0].headers[0] != "Referrer-Policy: no-referrer" {
		t.Errorf("blocks[0].headers = %+v, want [\"Referrer-Policy: no-referrer\"]", blocks[0].headers)
	}
}

// TestIsBlanketNoReferrerHeaderLineGapCase is the named gap case: a fallback list's effective
// value is its last token, so no-referrer earlier in the list must not count.
func TestIsBlanketNoReferrerHeaderLineGapCase(t *testing.T) {
	if !isBlanketNoReferrerHeaderLine("Referrer-Policy: strict-origin, no-referrer") {
		t.Error("no-referrer as the last token must be blanket")
	}
	if isBlanketNoReferrerHeaderLine("Referrer-Policy: no-referrer, strict-origin-when-cross-origin") {
		t.Error("no-referrer earlier in the list, not last, must not be blanket")
	}
}
