#!/usr/bin/env bash
# check-copy: the local half of `make check-copy` (tool/docs/design/copy-standard.md section 4.4).
# It runs two checks over the committed golden alone, never over Go source: a literal deny-list
# from the standard's own banned column (section 2.9) and forbidden-word list (section 2.10), and
# three structural rules a word list cannot express (a bare kebab token, a fix line with more
# than one comma before its first period, and any "!"). Vale, the standard's other half, runs
# separately through tool/.vale/copy.ini.
#
# Exit 1 naming tool/docs/design/copy-standard.md on any finding; 0 otherwise.
set -uo pipefail
cd "$(dirname "$0")/.."

GOLDEN="testdata/copy.golden.md"
STANDARD="tool/docs/design/copy-standard.md"

if [ ! -f "$GOLDEN" ]; then
  echo "check-copy: $GOLDEN does not exist; run 'make copy-list' first" >&2
  exit 1
fi

fail=0

# entries is every bullet line's own text, the "- " prefix stripped: the deny-list and the
# structural rules apply to the catalogue's entries, not to this file's own framing prose
# (its title, its "Generated by" note, and its "## <package>" headings).
entries="$(grep -E '^- ' "$GOLDEN" | sed -E 's/^- //')"

# deniedWords is the standard's own banned column (section 2.9) and forbidden-word list
# (section 2.10), curated to the terms a substring match can enforce without a false positive
# against a legitimate technical identifier this catalogue also carries (an npm package name, a
# file name, a DNS record type): the qualifier "in operator prose" on a handful of section 2.9's
# rows means those rows need a human reading, not a grep, and are left to the editorial gate
# (section 4.5) instead.
deniedWords=(
  "healthy" "degraded" "all clear" "no issues" "fine"
  "unavailable" "not observable" "indeterminate" "cred-missing"
  "acknowledged" "snoozed" "muted" "suppressed" "waived"
  "remedy" "remediation" "worklist" "action item" "next step" "resolution"
  "fleet" "estate" "inventory" "portfolio"
  "vault" "secret store" "credential manager" "secure storage"
  "last seen" "data age" "refreshed"
  "sorry" "unfortunately" "please" "simply" "just" "easily" "quickly" "merely"
  "note that" "please note"
)

for word in "${deniedWords[@]}"; do
  if grep -inE "\\b${word}\\b" <<<"$entries" >/dev/null; then
    echo "check-copy: banned word or phrase \"$word\" found in $GOLDEN (see $STANDARD section 2.9/2.10)" >&2
    grep -inE "\\b${word}\\b" <<<"$entries" | sed 's/^/  /' >&2
    fail=1
  fi
done

# A bare kebab token as a whole entry is a machine id sitting in a prose field, never a sentence
# (section 2.9's "the stable id of a failure mode" row and section 4.4's own structural rule).
while IFS= read -r line; do
  [ -z "$line" ] && continue
  if [[ "$line" =~ ^[a-z0-9]+(-[a-z0-9]+)+$ ]]; then
    echo "check-copy: entry \"$line\" is a bare kebab token, not prose (see $STANDARD section 2.9)" >&2
    fail=1
  fi
done <<<"$entries"

# A fix line with more than one comma before its first period reads as a run-on instruction
# (section 2.5: "No three-clause comma chains"). Only an entry ending in a period is a candidate
# at all: a detail line carries none (2.4's own "No final period" rule), so this is how the check
# reaches fix lines without needing the two tables kept apart.
while IFS= read -r line; do
  [ -z "$line" ] && continue
  [[ "$line" == *. ]] || continue
  before_period="${line%%.*}"
  commas="$(tr -cd ',' <<<"$before_period" | wc -c)"
  if [ "$commas" -gt 1 ]; then
    echo "check-copy: \"$line\" carries more than one comma before its first period (see $STANDARD section 2.5)" >&2
    fail=1
  fi
done <<<"$entries"

# No exclamation mark anywhere in the golden (section 2.10).
if grep -F '!' "$GOLDEN" >/dev/null; then
  echo "check-copy: an exclamation mark appears in $GOLDEN (see $STANDARD section 2.10)" >&2
  grep -nF '!' "$GOLDEN" | sed 's/^/  /' >&2
  fail=1
fi

if [ "$fail" -eq 0 ]; then
  echo "check-copy: vocabulary clean"
fi

if ! command -v vale >/dev/null 2>&1; then
  echo "check-copy: vale not installed; install it, do not skip the gate" >&2
  exit 1
fi

if vale --config .vale/copy.ini --minAlertLevel=error "$GOLDEN"; then
  echo "check-copy: vale clean"
else
  echo "check-copy: error-level Vale findings in $GOLDEN (above, see $STANDARD)." >&2
  fail=1
fi

exit "$fail"
